# Pytorch Tutorial !!

In [126]:
import torch

# float tensors

In [127]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[1, 2],
                       [1, 2]])

# Matrix multiplication 

In [128]:
c = torch.matmul(a, b)
c

tensor([[ 3.,  6.],
        [ 7., 14.]])

# Tensor Allocation

In [129]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [130]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt # 정수를 담는 롱텐서, 인덱스 같은 값을 담을때 많이 사용된다.

tensor([[1, 2],
        [3, 4]])

In [131]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
                       # 보통 0과 1을 담는다. 참 거짓을 많이 했는데 요즘은 불리언 텐서도 있다.
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [132]:
x = torch.FloatTensor(3, 2) # 값은 상관 없고 사이즈만 같게 텐서를 만들어주는 것.
x

tensor([[8.2991e+03, 4.5790e-41],
        [3.0060e-35, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

#NumPy Compatibility

In [133]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [134]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [135]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


# Tensor Type-casting

In [136]:
ft.long() # 롱타입으로 새롭게 바뀌는 것

tensor([[1, 2],
        [3, 4]])

In [137]:
lt.float() # 플롯타입으로 새롭게 바뀌는 것

tensor([[1., 2.],
        [3., 4.]])

In [138]:
torch.FloatTensor([1, 0]).byte() # 바이트타입으로 새롭게 바뀌는 것

tensor([1, 0], dtype=torch.uint8)

# Get Shape

In [139]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

#### Get tensor shape

In [140]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


#### Get number of dimensions in the tensor

In [141]:
print(x.dim())
print(len(x.size()))

3
3


#### Get number of elements in the last dimension

In [142]:
print(x.size(-1))
print(x.shape[-1])

2
2


# PyTorch Tensor Operations

#### Arithmetic Element-wise Operations

In [143]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [144]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [145]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [146]:
a * b

tensor([[ 2.,  4.],
        [ 9., 12.]])

In [147]:
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [148]:
a == b

tensor([[False,  True],
        [ True, False]])

In [149]:
a != b

tensor([[ True, False],
        [False,  True]])

In [150]:
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

#### Inplace Operations

In [151]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b)) #결과를 a에 넣는다. 주소값에 덮어쓰는 것이다. 속도의 이점이 크진 않다. 
                 #메모리를 새로 할당하지 않을 때 사용
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


# Sum, Mean (Dimension Reducing Operations)

In [152]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])

In [153]:
print(x.sum()) # 스칼라 값
print(x.mean()) # mean을 때려서 스칼라 값

tensor(10.)
tensor(2.5000)


In [154]:
print(x.sum(dim=0)) # 없어질 디멘션을 선택하는 것
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


# Broadcast in Operations

#### What we did before,

In [155]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [156]:
z = x + y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


#### Broadcast feature provides operations between different shape of tensors
Tensor + Scalar

In [157]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
y = 1

print(x.size())

torch.Size([2, 2])


In [158]:
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


#### Tensor + Vector

In [159]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3,
                       5])

# |x| = (2, 2) , |y| = (2,) => (1, 2) [[3, 5], [3, 5]] 처럼 해서 더해준다.
print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([2])


In [160]:
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [161]:
x = torch.FloatTensor([[[1, 2]]]) # |x| = (1, 1, 2), |y| = (2, ) => (1, 1, 2)로 틸다 해준다
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

torch.Size([1, 1, 2])
torch.Size([2])


In [162]:
z = x + y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


#### Tensor + Tensor

In [163]:
x = torch.FloatTensor([[1, 2]]) # |x~| 는 (2, 2), |y~| 는 (2, 2)
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [164]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


# Failure Case

In [165]:
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size()) # 어디에 1을 넣어도 차원 통일이 불가능 하다 => Broadcast 불가
print(y.size())

try:
  z = x + y
except Exception as e:
  print(e)

torch.Size([1, 2, 2])
torch.Size([3, 3])
The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2


# PyTorch Tensor Manipulations

# Tensor Shaping
# reshape: Change Tensor Shape

In [166]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())

torch.Size([3, 2, 2])


In [167]:
print(x.reshape(12)) # 12 = 3 * 2 * 2
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [168]:
print(x.reshape(3, 4)) # 3 * 4 = 3 * 2 * 2
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [169]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [170]:
print(x.reshape(3, 2, 2, 1))
# contiguous + view = reshape 텐서의 모양을 스플릿, 컨켓하면 
# 메모리에 이어져서 표현이 안되었어서
# 메모리에 다시 할당하는것에다가 뷰를 하는 것.

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


# squeeze: Remove dimension which has only one element.

In [171]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())  

torch.Size([1, 2, 2])


# Remove any dimension which has only one element.

In [172]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


# Remove certain dimension, if it has only one element. If it is not, there would be no change.

In [173]:
print(x.squeeze(0).size()) # 0은 1이기 때문에 없어진다.
print(x.squeeze(1).size()) # 특정 디멘션에만 해준다. 1번에서는 1이 없기 때문에 그대로 나온다.

torch.Size([2, 2])
torch.Size([1, 2, 2])


# unsqueeze: Insert dimension at certain index.

In [174]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [175]:
print(x.unsqueeze(2)) # 어떤 특정 디멘션에 1을 insert하는 것
print(x.unsqueeze(-1))
print(x.reshape(2, 2, -1)) # 3개다 2x2x1로 해준다

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])


# Slicing and Concatenation

#### Indexing and Slicing
##### Prepare target tensor.

In [176]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


##### Access to certain dimension.

In [177]:
print(x[0])
print(x[0, :])
print(x[0, :, :])

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [178]:
print(x[-1])
print(x[-1, :])
print(x[-1, :, :])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [179]:
print(x[:, 0, :])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


#### Access by range. Note that the number of dimensions would not be changed.

In [180]:
print(x[1:3, :, :].size())
print(x[:, :1, :].size()) # range의 특징은 해당 디멘젼이 없어지지 않는다. 인덱스와 차이점
print(x[:, :-1, :].size())

torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


#### cat: Concatenation of multiple tensors in the list.

In [181]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [182]:
z = torch.cat([x, y], dim=0)
print(z)
print(z.size()) # |[x;y]| = (6, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [183]:
z = torch.cat([x, y], dim=-1)
print(z)
print(z.size())# |[x;y]| = (3, 6) # 기존의 존재하는 차원에 붙히는 것

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


#### stack: Stacking of multiple tensors in the list.

In [184]:
z = torch.stack([x, y])
print(z)
print(z.size()) # 쌓는 것, 차원이 하나 더 생긴 것. unsqueeze 하고 붙힌다는 의미와 같다
# (3, 3) => (1, 3, 3) 2개 합치니, (2, 3, 3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


#### Or you can specify the dimension. Default is 0.

In [185]:
z = torch.stack([x, y], dim=-1) # 뒤로 디멘션 만들고 붙히기
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


#### Implement 'stack' function by using 'cat'.

In [186]:
# z = torch.stack([x, y])
z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
